spring.application.name=testdemo

spring.datasource.url = jdbc:mysql://localhost:3306/springboot_test
spring.datasource.username = root
spring.datasource.password = Root123456!
server.port=8081
# spring boot ????3306???MySQL???springboot_test????????
mybatis.mapper-locations = classpath:mapper/*.xml


